services:
  resilmesh-sop-pt-frontend:
    image: ghcr.io/shuffle/shuffle-frontend:latest
    container_name: resilmesh-sop-pt-frontend
    hostname: resilmesh-sop-pt-frontend
    expose:
      - 80
      - 443
    ports:
      - ${PT_FRONTEND_PORT}:443
    networks:
      resilmesh:
    environment:
      - BACKEND_HOSTNAME=resilmesh-sop-pt
    restart: unless-stopped
    depends_on:
      - resilmesh-sop-pt
  resilmesh-sop-pt:
    image: ghcr.io/shuffle/shuffle-backend:latest
    container_name: resilmesh-sop-pt
    hostname: resilmesh-sop-pt
    expose:
      - 5001
    networks:
      resilmesh:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/apps:/shuffle-apps:z
      - ./volumes/files:/shuffle-files:z
    env_file: container.env
    environment:
      - SHUFFLE_APP_HOTLOAD_FOLDER=/shuffle-apps
      - SHUFFLE_FILE_LOCATION=/shuffle-files
      - SHUFFLE_OPENSEARCH_PASSWORD=${PT_OPENSEARCH_PASSWORD}
    restart: unless-stopped
  resilmesh-sop-pt-orborus:
    image: ghcr.io/shuffle/shuffle-orborus:latest
    container_name: resilmesh-sop-pt-orborus
    hostname: resilmesh-sop-pt-orborus
    networks:
      resilmesh:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: container.env
    environment:
      - SHUFFLE_APP_SDK_TIMEOUT=300
      - SHUFFLE_ORBORUS_EXECUTION_CONCURRENCY=7
      - ENVIRONMENT_NAME=Shuffle
      - ORG_ID=Shuffle
      - BASE_URL=http://resilmesh-sop-pt:5001
      - DOCKER_API_VERSION=1.40
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - SHUFFLE_PASS_WORKER_PROXY=TRUE
      - SHUFFLE_PASS_APP_PROXY=TRUE
      - SHUFFLE_STATS_DISABLED=true
      - SHUFFLE_LOGS_DISABLED=true
      # - SHUFFLE_SWARM_CONFIG=run
      - SHUFFLE_WORKER_IMAGE=ghcr.io/shuffle/shuffle-worker:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
  resilmesh-sop-pt-opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: resilmesh-sop-pt-opensearch
    hostname: resilmesh-sop-pt-opensearch
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - bootstrap.memory_lock=true
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - cluster.initial_master_nodes=pt_opensearch
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=shuffle-cluster
      - node.name=pt_opensearch
      - node.store.allow_mmap=false
      - discovery.seed_hosts=pt_opensearch
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${PT_OPENSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - shuffle-database:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      resilmesh:
    restart: unless-stopped

  #memcached:
  #  image: memcached:latest
  #  container_name: shuffle-cache
  #  hostname: shuffle-cache
  #  mem_limit: 1024m
  #  environment:
  #    - MEMCACHED_MEMORY=1024
  #    - MEMCACHED_MAX_CONNECTIONS=2500
  #  ports:
  #    - 11211:11211

  #docker-socket-proxy:
  #  image: tecnativa/docker-socket-proxy
  #  container_name: docker-socket-proxy
  #  hostname: docker-socket-proxy
  #  privileged: true
  #  environment:
  #    - SERVICES=1
  #    - TASKS=1
  #    - NETWORKS=1
  #    - NODES=1
  #    - BUILD=1
  #    - IMAGES=1
  #    - GRPC=1
  #    - CONTAINERS=1
  #    - PLUGINS=1
  #    - SYSTEM=1
  #    - VOLUMES=1
  #    - INFO=1
  #    - DISTRIBUTION=1
  #    - POST=1
  #    - AUTH=1
  #    - SECRETS=1
  #    - SWARM=1
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  networks:
  #    - shuffle
  #

volumes:
  shuffle-database:
    name: pt-opensearch-db

networks:
  resilmesh:
    external: true
    name: resilmesh_network
    # uncomment to set MTU for swarm mode.
    # MTU should be whatever is your host's preferred MTU is.
    # Refer to this doc to figure out what your host's MTU is:
    # https://shuffler.io/docs/troubleshooting#TLS_timeout_error/Timeout_Errors/EOF_Errors
    # driver_opts:
    #   com.docker.network.driver.mtu: 1460
